# Usa la imagen oficial de Ubuntu como base
FROM ubuntu:latest

# Instala actualizaciones y paquetes necesarios
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git \
    python3 \
    python3-venv \
    python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Crea una carpeta de trabajo
WORKDIR /Copa_Test

# Clona el repositorio de GitHub
RUN git clone https://github.com/bhirschb16/Copa.git

# Establece el directorio de trabajo dentro del repositorio clonado
WORKDIR /Copa_Test/Copa

# Crea y activa el entorno virtual Python
#RUN python3 -m venv Copa_Venv && \
#    . Copa_Venv/bin/activate && \
#    pip install --no-cache-dir -r requirements.txt

# CMD o ENTRYPOINT para ejecutar tu script Python
#CMD ["python", "0_creacion_bd_postgres.py"]
